os:
  - osx
  
osx_image: xcode8.3
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install
  
script:
  - node_modules/.bin/electron-builder --mac

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
